deploy:
  image: docker:latest
  stage: deploy
  tags:
    - "dind"
  script:
    - docker build -t registry.hal.davecutting.uk/40266405/qubgrademe-frontend .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push registry.hal.davecutting.uk/40266405/qubgrademe-frontend