FROM openjdk:20-ea-19-jdk
COPY target/qubgrademe-averagegrade-0.0.1-SNAPSHOT.jar qubgrademe-averagegrade-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/qubgrademe-averagegrade-0.0.1-SNAPSHOT.jar"]